### ISSUE TITLE
min and max sensor values

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#101]
As member of service team,
I want to add min and max values at sensor setting page
to define the covered range of my sensor-live-report.

**Comment by roschaefer** [comment]
Remember: If we define this for every `Sensor` and not `SensorType`, it will load a lot of manual labour on the service team.

**Comment by roschaefer** [comment]
I would actually prefer `SensorType` for reasons of consistency. It's the record in the database that holds descriptive information like `unit` and `property`.

**Comment by roschaefer** [comment]
was just added to the `SensorType`
