### ISSUE TITLE
UPDATE Sensortype Preis

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#106]
Sensortype Preis should use unit Cent (nor €) without punctiuation (25 Cent).

**Comment by roschaefer** [comment]
that's actually not a bug

**Comment by drjakob** [comment]
A feature?

**Comment by roschaefer** [comment]
`Change` maybe. I would just like to use `BUG` for behaviour that obviously violates the specified behaviour or produces errors. Must be fixed in a timely manner.

**Comment by roschaefer** [comment]
just implemented in #487
