### ISSUE TITLE
Report: Insert break and add sub-headings

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#108]
As a reader
I would like to have sensor-live-reports structured in paragraphs
Because small chunks of texts are easier to read

Details: 
* Every 500+ characters an automated break after last text component
* Heading of next text component becomes subheading

**Comment by roschaefer** [comment]
We can easily add breaks after number of characters. But unfortunately there is no *next* text component right now, as we don't have a defined total order among text components:

1. Choose the main heading
2. Always start introduction and main_part etc. with the text component of the main heading
3. If the text gets too long:
3.1: Make a break
3.2 Find the text component that would go next and insert its heading (which can't be the main heading)

I don't know if it's worth the effort. I would prefer the [KISS](https://en.wikipedia.org/wiki/KISS_principle) solution - only breaks.

**Comment by drjakob** [comment]
Subheads with text.component queue possible?
