### ISSUE TITLE
Report: Order equally prioritized text components randomly

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#109]
As a reporter
I want text components to be ordered randomly if they have the same priority
In order to obscure the algorithmic generation of the report

**Comment by roschaefer** [comment]
This is similar to #87 right? How many `text_components` should populate the introduction at maximum?

**Comment by drjakob** [comment]
Think this should be a variable in settings if possible because its a fine-tuning feature.

**Comment by drjakob** [comment]
Otherwise: three.

**Comment by roschaefer** [comment]
implemented, see [this spec](https://github.com/roschaefer/story.board/blob/master/spec/text/sorter_spec.rb#L56)
