### ISSUE TITLE
Is time just a sensor?

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#110]
@roschaefer: What about daytime as a condition for textcomponents. We can model it as a sensor, can't we?

USER STORY:
As a reporter I want to
set a time frame for my text component
to have text components for daily repeatated tasks.

**Comment by roschaefer** [comment]
We could model the time as a sensor event, yes. But this sounds a bit like a [golden hammer](https://en.wikipedia.org/wiki/Law_of_the_instrument). Let's just specify the purpose of the feature and the engineers will find a solution. So you want to have a text component triggered e.g. every morning, right? Then this sounds very similar to #24
