### ISSUE TITLE
TextComponents: Render Markup in headings and QuestionAnswers

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#112]
As a reporter
I want to render markup for literally every input field of text components, including question answers and the heading
Because even in the heading I want to refer to the main actor, e.g. "What's up, Bertha?"

**Comment by roschaefer** [comment]
Text components are listed with their headings. That's why I left out the markup in the headings. Do we want this feature? I would imagine it to be quite confusing.

**Comment by drjakob** [comment]
Its a bit confusing. But I think important. Caharcters are often named in "old news" headlines.
