### ISSUE TITLE
Event: Implement a new model

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#117]
As a reporter 
I want to track events in my database - each has happened at a certain time or has not happened at all
To consider some non-numeric important information, e.g.  "birth", "regular vet control", "christmas".

**Comment by drjakob** [comment]
Example Case: http://bit.ly/2bzyB6o
(password protected)

**Comment by drjakob** [comment]
Or do I need a planing tool for predicted events? Are events different from sensor measurements?

**Comment by roschaefer** [comment]
We need a tool to create sensor events manually. Similar to fake data.

**Comment by roschaefer** [comment]
Events are different to sensor readings as we have only numeric values for sensor readings right now. Maybe it's worth to add another model for this.
