### ISSUE TITLE
LiveReport: Choose between data bases

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/story.board#12]
As a journalist
I want to switch between different data sources, e.g. fake data
In order generate a preview of my live report from fake data

**Comment by drjakob** [comment]
data sources = input field or live sensor data

**Comment by drjakob** [comment]
identical with #11?

**Comment by roschaefer** [comment]
No but #11 is kind of a prerequisite. Given I *have* fake data, I want to switch between fake and real data.

**Comment by drjakob** [comment]
ok.
