### ISSUE TITLE
Events Bug

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#131]
As a reporter
i want to define and work with events
which haven't hppen yet. Should be possible to hoose a state "Never happened"

**Comment by roschaefer** [comment]
If you create an event, there is no `happened_at` attribute. It has *has not happened yet*. If you edit the the event, you can provide a date for the event and make it happen.

**Comment by drjakob** [comment]
Ok, but why can't I revert to "not happened". Would be very useful.
