### ISSUE TITLE
Trigger: New model

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/story.board#168]
As a journalist
I want to collect and store a set of conditions into a `Trigger` object, ie.
* sensor conditions
* manual events
* regular time frames (e.g. every day 10:00 - 12:00)
* aging (we call it "timeliness constraint")
* priority
* a random likelihood

Because a trigger represents a certain situation and therefore has a meaning to me

**Comment by roschaefer** [comment]
@drjakob have a look

**Comment by drjakob** [comment]
Looks good for me. 
Dont forget adding  Randomness to Trigger

**Comment by drjakob** [comment]
And Julian added Trigger-Color.

**Comment by drjakob** [comment]
@roschaefer So lets implement Randomness and Trigger Color
