### ISSUE TITLE
FEATURE REQUEST: Keys = Elements

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#171]
I think keys are sort of Elements (Not "Settings").

**Comment by roschaefer** [comment]
Actually, `Settings` is misnamed. It should be `Reports`. Currently it's just one. In the report settings you can change not only `keys` and `values` but also the start and the duration of the report.

Shall I rename `Settings` to `Reports` then?

**Comment by drjakob** [comment]
Yes, Please.
