### ISSUE TITLE
BUG with Preview

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#179]
Selection of text.components not working (in preview).

**Comment by drjakob** [comment]
Seems it doesn't use timespan (eg component Hochleistungsherde)

**Comment by roschaefer** [comment]
I don't understand the problem here. In both preview and real mode, I can see that component "Die Herde ist in Bestform" is added to the report

**Comment by drjakob** [comment]
Yes, but should only be added between day 101 and 103. And its added aways!?

**Comment by roschaefer** [comment]
Ha, good one! Text components have the attribute but there is [no feature](https://github.com/roschaefer/story.board/tree/master/features/text_components) that the attributes are actually used. This happened due to code generation. Covered in #16
