### ISSUE TITLE
Sensor.bot: Archive a former report

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/story.board#19]
As a journalist
I want old reports to be archived
In order to read about what happened earlier

**Comment by drjakob** [comment]
Is point:5 ist correct for this task?

**Comment by roschaefer** [comment]
@drjakob I asked myself the same question. Maybe this is too pessimistic. The reason why I thought this could become more difficult than it seems is that [Jekyll](https://jekyllrb.com/) took care of blogging and archiving in our prototype [Ursuppe](https://github.com/roschaefer/Ursuppe). So I have to do research what's a good direction for the future. Is it possible to integrate functionality of Jekyll? Or should we develop our own blogging framework somehow. But you're right, in the case we simply create another record in our database, this is probably done in an hour.

**Comment by drjakob** [comment]
No, just output as xml seems fine. Lets focus.

**Comment by roschaefer** [comment]
closed via #91
