### ISSUE TITLE
Connect UX-Sliders with Ruby functions PLEASE CHECK

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#204]
PLEASE CHECK if the sliders in create text.component are functional.

**Comment by roschaefer** [comment]
I'm currently reviewing this issue, there are two visible sliders: One for the timeliness constraint (awful naming btw.) and for the sensor conditions.

* If I create a text component along with a new trigger
  + sensor conditions are set up for the trigger
  + timeliness constraint is set with the trigger

However
* If I create a text component along with a new trigger
  - there is no visual separation between attributes for the trigger and for the text component (like a box)
  - double checking the attributes is cumbersome, you have to click on `TextComponent>>Show` and `Triggers>>Show` until you get to the trigger attributes
  - The Trigger does not show the actual values for the SensorConditions but defaults, which is not only a UX problem but also a functional problem

**Comment by roschaefer** [comment]
It is also possible to have different sensor conditions for the same sensor:
![selection_130](https://cloud.githubusercontent.com/assets/2110676/24553732/71195230-162b-11e7-929b-bd7b09f784e9.png)
