### ISSUE TITLE
TextComponent#edit: INGREDIENTS MENU Buttons to include markup at cursor position

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#207]
As a reporter, when I edit the text parts of a text component
I want to have buttons for all sensors and events, to include their markup at the current cursor position
In order to reduce errors and to input markup comfortably

**Comment by roschaefer** [comment]
hey @tillprochaska if you say "close #207" in the description of a pull request, the issue will be auto-closed as soon as the PR is merged into master
