### ISSUE TITLE
Sensor#edit: Enter sensor reading manually

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#209]
As a reporter
I want to manually enter sensor readings
In case the human being is the only sensor who is able to detect a certain physical value

**Comment by roschaefer** [comment]
@drjakob it is already possible to let an event happen, see [this feature](https://github.com/roschaefer/story.board/blob/68ff86c35be695e09047ffc2c05aec5129a956a9/features/triggers/write_about_an_event.feature).

**Comment by drjakob** [comment]
Its not about events, but about an input for sensor values. (eg. a sensor failed and we have to do input by human)
