### ISSUE TITLE
TextComponent: Add location

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#211]
As a reporter
I want to tag text components with geo locations
In order to generate a location-aware sensor live report

–> solution location as a a property. In which relation to location property of sensors?

**Comment by roschaefer** [comment]
I don't understand "–> solution location as a a property. In which relation to location property of sensors?"

**Comment by roschaefer** [comment]
@drjakob keep in mind the value to the customer. Is this really `priority: high`?
