### ISSUE TITLE
Report: Add location

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#213]
As member of service team
I want to add, edit and delete locations in settings menu
because there are different locations where my sensor report should take place. These locations should be base for text component locations (#211) and sensor locations (#212)

**Comment by roschaefer** [comment]
@drjakob could you please explain how the report will change if we add geo location to the reports? Of course, different reports will cover different cow-sheds. But how should the algorithm change, if we add geo location to reports?
