### ISSUE TITLE
Sensor group as ingredient (and condition)

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#215]
As a reporter
I want to insert the values of a sensor group to my text component
because there are different sensors dependent on location.
eg. {sensor-group-temperature} with sensors temperature_kitchen, temperature_bathroom, temperature_living_room should use the sensor of the location the output is for (see #214) .

**Comment by roschaefer** [comment]
What does that mean? Should there be a common (average) temperature within a sensor group? A text component should be triggered by this value instead?

If this is correct, my advise is to dismiss this feature. It adds complexity to everything, the report, editing text components and sensor groups. In my point of view, the obscure advantage of this feature does not pay off at all for the added complexity for both computer and human.
