### ISSUE TITLE
TextComponent#edit: Time range with dropdown

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#221]
As a reporter
I want to define a time span with two clicks in a dropdown menu
Because it is contra-inductive to input two numbers for time.

example:
[https://i.stack.imgur.com/zCTNY.png](url)

**Comment by roschaefer** [comment]
@drjakob 404 error for the link

**Comment by drjakob** [comment]
Think should be possible to do in one or two hours: Two simple dropdown Menus with hours 0-23h
