### ISSUE TITLE
TextComponent#index: Add text component button at the top

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#226]
As a reporter
I want to add a new text component quickly. Create Text Component: Button for "New Text Component" Should also be aside the headline

**Comment by roschaefer** [comment]
Are two "Add" buttons OK? (One at the top, one at the bottom?) I'm not a designer, but I think there are even conventions where users would expect "Add" buttons..

**Comment by drjakob** [comment]
Yes, two would be fine
