### ISSUE TITLE
TextComponent#create: Write about the actual sensor value

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/story.board#23]
As a journalist
I want to include the actual value of a sensor in a text component
So I can tell the reader that a particular value of e.g. 970 hPa is quite low

**Comment by drjakob** [comment]
middle or high?

**Comment by roschaefer** [comment]
Dunno :smile: I stumbled upon this because I checked the functionality of our [prototype](https://github.com/roschaefer/Ursuppe)

**Comment by drjakob** [comment]
Stll *very important* issue. I want to use "{value}", should replaced by value of sensor.
