### ISSUE TITLE
Text Component: Output to… option

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#240]
As a reporter
I want to have  an option for "Output to…" multi-selection for each text.component.  First output-choices to be impemented should be checkbox "Send to Chatbot" (default: off) and "Send to Story" (default: on) because I want to write specific text.components for specific outputs.

**Comment by roschaefer** [comment]
Can you be a little more specific? What does it mean "Send to Chatbot"? When should the text be displayed in the chatbot? Whenever someone writes something?

Also I would try to keep as much data as possible in Chatfuel. Chatfuel has a rich user interface already.

We're developing a piece of software for 30 days. The integration of all data sources into one would be nice to have, but probably too expensive for us.

**Comment by drjakob** [comment]
– "Send to Chatbot" qualifies a text component general to be sent to a chatbot.
I am really looking for a solution as slim as possible.

Think of a text component with the main content:
 "Its 28°. This is to hot. | Flies like high temperatures. We hate flies. So we like it cold."

Send to Chatbot: TRUE. 
Button text: "Why?"

If Chatfuel is sending a request to  our API for e.g. "temperature." We send "Its 28°. This is to hot.""+BUTTON "Why?"
If user presses button Chatfuel is asking for "temperature, part two". Then we send "Flies like high temperatures. We hate flies. So we like it cold."
So:

– All chatbot data we store in storyboard is: the "id" (=block name "temperature") used by chatfuel, our dynamical text (splitted in two parts by "|") and the linking question. I can't see how we can reduce this any more.

**Comment by drjakob** [comment]
I think we'll have 3 or 4 possible output channels with their own options (Website, Chatbot, Newsletter, Website Media-Partner…). Could be, that one output channel ist for kids, so that you want to block some text.components with "cruel" information.

**Comment by roschaefer** [comment]
This sounds similar to #243 except that we talk about different platforms or websites here. When I say `Channel` I could also say `Topic`. Think of a slack channel.

If we talk about different media I would suggest that we have to learn what are the different needs for every media and *then* start to implement that.
