### ISSUE TITLE
Chatbot request handler (=Story.board API?)

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#241]
As a reporter
I want story.board to answer to Chatfuel requests as follows:  (1) Select text components with active output channel chatbot (checkbox chatbot checked as in #240) (2) and thespecific block requested by chatbot ( #243 "TEMPERATURE" or "BEWEGUNG" or…) (3) and only select text components with an active trigger  and (4) deliver it to chatbot (selected via #243) (5) with a read more button ( #248) 
because I want to output dynamic content of the chatbot system.

**Comment by roschaefer** [comment]
@drjakob could you explain this a little more? AFAIK except (5) this should be implemented.

BTW. I think these kinds of super user stories are called "epics" in Zenhub. Maybe you can check that out ;)
