### ISSUE TITLE
Text Component: Add many pieces of additional information

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#242]
As a reporter 
I want to add arbitrary many question/answer text fields to the main part of a component
In order to provide the data for the *Read more* button in Chatfuel

**Comment by roschaefer** [comment]
How about a different text field?

**Comment by drjakob** [comment]
I think the markup is more dynamic because you can use it 0,1,2,3… times.

**Comment by roschaefer** [comment]
Then let's use [Cocoon](https://github.com/nathanvda/cocoon) for dynamic nested forms

**Comment by roschaefer** [comment]
@drjakob I updated the user story, does that fit your needs?
