### ISSUE TITLE
ChatFuel: Call a channel

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/story.board#258]
As a reader who uses Facebook Messenger
I want to click on a button e.g. `Milk` and get all the recent news and data about milk
To satisfy my interest in different areas

**Comment by drjakob** [comment]
"all the recent news": Precise information in a really short form, sentence for sentence (by button request)

**Comment by leifg** [comment]
`click on a button`

In Facebook?

**Comment by roschaefer** [comment]
@leifg yup

**Comment by drjakob** [comment]
Click a button in Facebook Messenger (!)

**Comment by roschaefer** [comment]
@drjakob if we have different text components for different channels you can write a short text component for Facebook and a longer one for our report

**Comment by drjakob** [comment]
@roschaefer Correct, thats the plan. (What I meant: The scenario for messenger is about really short pieces of text.)

**Comment by roschaefer** [comment]
closed through #266
