### ISSUE TITLE
Sensors: Deactivate

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#285]
As member of the srevice team
i want to switch off certain sensors
in order to eliminate failing sensors and to prevent to much noise.

**Comment by roschaefer** [comment]
To be considered: Reporters might forget to activate sensors again. Please think about the actual value (debugging). In which situation do you want this? Would it be better to have a "debugging view" where you can switch off e.g. sensors or maybe just triggers?

ping @drjakob

**Comment by drjakob** [comment]
close
