### ISSUE TITLE
Missing data after installation

### ISSUE THREAD

**Issue by matthib** [roschaefer/story.board#297]
I followed the installation instructions to run the project on my local machine, but the project doesn't seem to work.

There seems to be data in the database missing after the local installation, which are expected to be there by the project.

![story_board_error1](https://cloud.githubusercontent.com/assets/12625174/24334247/8098f584-1267-11e7-98a0-8ae035e7923e.PNG)

**Comment by roschaefer** [comment]
ah, this is already covered by #296
