### ISSUE TITLE
Add missing data to seed file

### ISSUE THREAD

**Issue by matthib** [roschaefer/story.board#298]
Add the missing data to seed file, so they are available in the database and the project can work as expected.

Missing data contains among others the channels (only channel "storyboard" is added to the db, but later channels "chatbot" and "sensorstory" are accessed).

**Comment by roschaefer** [comment]
@matthib if you write "close #298" in your description of your pull request, this will automagically close the issue with that number as soon as your PR is merged, see: https://github.com/blog/1506-closing-issues-via-pull-requests
