### ISSUE TITLE
Chatbot: Read more

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#307]
As a reporter
I want the storyboard api to deliver a specific question/answer identified by a number as parameter to chatfuel. (Request: "Channel chatbot/milkquantity, q&a no.1", second Request: "Channel chatbot/milkquantity, q&a no.2")

**Comment by roschaefer** [comment]
@matthib I guess this is related to #248. How does Chatfuel actually know which question was already "seen" by the user?

**Comment by drjakob** [comment]
Very dumb & easy implementation:
Chatfuel sends five api requests to story.board for block1,block2,block3,block4,block5. And gets back the desired block – or nothing (if no q&a defined).
CHATFUEL: send me milk_quantity, block no.1
story.board api: "I am a cow." ,Button: "So you giving milk?"
CHATFUEL: send me milk_quantity, block no.2
story.board api: "Sure." , Button: "How much?"
CHATFUEL: send me milk_quantity, no.3
story.board api: "Up to 50 litres a day" , Button: "Thats much milk."
CHATFUEL: send me milk_quantity, no.4
story.board api: "NIL"
CHATFUEL: send me milk_quantity, no.5
story.board api: "NIL"

**Comment by roschaefer** [comment]
Yep, the question was how does Chatfuel know what question-answer of a text component a user requested?

**Comment by drjakob** [comment]
Its a linear, fix coded, dumb solution in Chatfuel – so not at all problem by story.board. 

Think about it as five fixed-coded api requests in Chatfuel:
CHATFUEL: send me milk_quantity, no.1
(waiting if user clicks  button)
CHATFUEL: send me milk_quantity, no.2
(waiting if user clicks  button)
CHATFUEL: send me milk_quantity, no.3
(waiting if user clicks  button)
CHATFUEL: send me milk_quantity, no.3
(waiting if user clicks  button)
CHATFUEL: send me milk_quantity, no.4
(waiting if user clicks button)
CONTINUE WITH BLOCK 54

**Comment by matthib** [comment]
My implementation looks like this currently:

There is an api request for a specific topic like this: http://localhost:3000/chatfuel/1
If there are questions and answers attached to the text component of the topic, a button is attached to the response with the first question (as the text) and the url of the api request for the answer.

The api request currently looks like this: http://localhost:3000/chatfuel/1/qa/1
This will return the answer of the first question together with a button for the second question (if one exists) and the api request for the second answer (http://localhost:3000/chatfuel/1/qa/2).

This means essentially the user will see all question and answers (as long as there are any) one after another.

As far as i understand the process is a bit different in this issue:
An api request is sent to the sensorstory api to show question and answer with the id 1 (like this for example http://localhost:3000/chatfuel/1/question/1). Now the sensorstory api returns the question as button together with the url for the answer to chatfuel (for example http://localhost:3000/chatfuel/1/answer/1). If the user clicks the button, the sensorstory api will send back the answer for the requested question.

In this case this is only limited to one specific question and answer and the user doesn't see the next question and answer.

**Comment by drjakob** [comment]
Your solution seems to be smarter than the one I had in mind.
