### ISSUE TITLE
TextComponents: Add order to question_answers

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#309]
As a reporter
I want to see an index for every question-answer pair when I edit a text component
To see their order and total amount

**Comment by roschaefer** [comment]
@drjakob what do you mean by `main` is question 1. Do you mean the main part of the text component? The main part will not be shown as a button in Chatfuel.

**Comment by drjakob** [comment]
Ok, than I misunderstood the logic. Then please begin with question 1.
