### ISSUE TITLE
TextComponent: publication_status

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#310]
As a reporter
I want to have a flag for text.components (draft, fact-checked, published) and only published text components should be included in the report
In order to add new text components without affecting the result of the live report

**Comment by roschaefer** [comment]
Adding another attribute like `publication_state` is no big deal. But what's the bigger picture, what are we going to do with the `publication_state`?

**Comment by drjakob** [comment]
Only text.components with state published should be used for output.
This allows to work on the report while it is live.

**Comment by roschaefer** [comment]
Ok, get it. Again, this adds more complexity. Our reporters have to remember to set the flag on `published` when they are done. More things to keep in mind, more potential error causes. @drjakob @CowboyBjoern  are you sure?

**Comment by roschaefer** [comment]
re-estimated to 1. Most of the work has to be done in #311

**Comment by drjakob** [comment]
Yes, we are sure. Its part if a normal editorial workflow.
