### ISSUE TITLE
TextComponents: get to #show after save and have a button to show the #edit modal

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#312]
As a reporter (Björn),
I wish to have an edit button in the view of the text component (which I get to see after I created a new component)
in order to correct mistakes.

**Comment by roschaefer** [comment]
@CowboyBjoern 
1. When I successfully create a TextComponent I want to be redirected to the `show` page
2. The show page will display an `edit` button, which will show the same modal dialog "Edit text component" like on the `index` page

This is the [`index` page](https://vicari.perseus.uberspace.de/text_components), and this [a `show` page of a text component](https://vicari.perseus.uberspace.de/text_components/62).

Is this the desired behaviour?

**Comment by drjakob** [comment]
yes, i think so.

**Comment by drjakob** [comment]
Why is this estimated to last five hours?
