### ISSUE TITLE
TextComponent: Assignee

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#315]
As a editor in lead 
I want to set an assignee for every text.component 
To manage responsibilities among the team

---
use a dropdown menu

**Comment by roschaefer** [comment]
depends on #14

**Comment by roschaefer** [comment]
what shall happen if a user was assigned? Email notification?

**Comment by roschaefer** [comment]
@drjakob this is estimated 2 hours only because there is no effect of setting an assignee. Except displaying the assignee. Having notifications of some sort will make another user story.

**Comment by drjakob** [comment]
Ok, thats fine

-- 
Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 720 50 27

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage

**Comment by drjakob** [comment]
No, just a filter option for the list. To get your personal work.

-- 
Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 720 50 27

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage
