### ISSUE TITLE
Freetext communication field for text.components

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#316]
As a reporter
I want save notes for every text component
To provide e.g. information sources to our fact checkers
at the BOTTOM of create new text component-modal window.

**Comment by mz99** [comment]
Should this be an additional text field under the Text section (Title/Introduction/Main Part/Closing/Notes) or added on as a separate section by itself?

**Comment by roschaefer** [comment]
It's just an additional field under title/introduction/main etc. It will NOT be included in the report. It should be shown on the top of the form, to attract attention of the one who is editing the text component.

**Comment by drjakob** [comment]
A seperate ection at the bottom.

**Comment by drjakob** [comment]
This is highly requested for months now.

**Comment by tillprochaska** [comment]
@drjakob: I’m currently implementing this! :)

**Comment by roschaefer** [comment]
@tillprochaska the editors abused the `closing` attribute of the text component for the comments. Maybe you can check how many *actual* closings we have and just turn it into the comment field.

**Comment by drjakob** [comment]
@roschaefer No, this would be a dirty fix for the current project. (With UX and algorithmic implications etc.) Please lets get a new field for this new purpose.
