### ISSUE TITLE
Define Sensors

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#32]
As service-team
I want to define sensor-types and I2C-adresses for all customers and experiments
because I want to provide new types of sensors for new experiments. [modular system]

**Comment by roschaefer** [comment]
@drjakob this is a valuable feature. Is the collection of available sensors for all customers and for all experiments the same? Because then I will create a ```db/seeds/rb``` file to populate the story.board with the necessary data.

**Comment by drjakob** [comment]
Yes.
