### ISSUE TITLE
TextComponent#edit: Not all QuestionAnswers are shown

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#323]
Bug: if i edit a text.component only one pair of question/answer is shown instead of all existing.

**Comment by roschaefer** [comment]
But that's intended behaviour, no? For one text component, only one question is shown at a time. A click on the question should reveal the next question for that component. If you have several text components, there are many questions visible, ie. one each.


 

-------- Original message --------

**Comment by drjakob** [comment]
I am talking about the editing mode for reporters. In the modal only one q&a is shown.

-- 
Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 720 50 27

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage

**Comment by drjakob** [comment]
only ipad problem

**Comment by matthib** [comment]
Tested on iPhone (@matthib) and iPad (@drjakob) and the issue doesn't seem to occur anymore, so It can be closed.
