### ISSUE TITLE
TextComponents List: Enhance structure and styling

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#338]
As a reporter
I want to have a better colored user interface like in UX-Design-Sketch " 161007_SensorJournalismus1-01.png"
in order to have a better overview using the system.

**Comment by tillprochaska** [comment]
Estimated to 0, will explore possibilities in #336

**Comment by tillprochaska** [comment]
@drjakob You mean the table of text components, right?

**Comment by drjakob** [comment]
Yes.

-- 
Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 720 50 27

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage
