### ISSUE TITLE
Menu: Report toolbox

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#343]
As a reporter
I want to use the grey "Report"-Box as Main-Toolbox with functions
1. Active Report: [Kuh Bertha]
2. "Create New Text Component".
3. View  Text Components assigned to me* (Link available under Login)
4. View Test-Report
5. View Live-Report
*(tcs assigned to me)
For greater usability

**Comment by roschaefer** [comment]
@drjakob can you give me a quick feedback on what's missing here? As far I can tell, there is no `Create new text component` on the landing page. Though I think  it's confusing to have it there - a button would link to `/reports/:id/text_components/` and open the modal. That would be confusing, no? It's changing the route *and* opening a modal.

How do you want the toolbox to be?

**Comment by drjakob** [comment]
– UX Design proposed to make this a quick link-menu for the most used functions.
– I don't think that opening the modal will be confusing. "Create New Textcomponent" will be the second most used function for editors. So I think it will be useful to have this link on every page available. Why do you think its confusing?
– View Text Components assigned to me* (Link available under Login) will be one of the most used functions, so it would be good to have this as a one click option everywhere. 
– The switching between reports have to be clear. So the "Other reports" just need one Link titled ("switch to this report") (could be actual Preview-Link)
