### ISSUE TITLE
BUG inserted markup by menu will not render

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#358]
The inserted markup in text.component create via new menu is not rendered correctly. 
– Sensor-Markup should Output the Sensor value, e.g. 37° C
– Event-Markup should Output the Date and Time in German Format (important!), eg. 27. Mai, 9:17 Uhr.

**Comment by drjakob** [comment]
Replaceery markup

**Comment by drjakob** [comment]
Markup in Channel Chatbot is not rendered at all.

**Comment by tillprochaska** [comment]
@roschaefer/@matthib: I’m not really familiar with that whole thing about chatfuel so I’ll go the lazy route and just ask you! Has this actually been implemented for the Chatfuel interface?

**Comment by roschaefer** [comment]
I have no idea either

**Comment by roschaefer** [comment]
it looks as if there is an implementation for the `main_part` but not for the `question_answers`: https://github.com/roschaefer/story.board/blob/master/app/controllers/chatfuel_controller.rb#L39
