### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#371]

**Comment by roschaefer** [comment]
By `debugging` I don't mean a single time to debug: I helped both @matthib and @mz99 on their issues. Especially #363 took so long to debug! Together with my own issues I spend the entire weekend working on this project and neglected my other duties (Rundfunk MITBESTIMMEN and expecially my master thesis). So I just want to have less workload for next sprint, as it is to be expected that I will help other team members (spending time) again. E..g. this time it was 8 hours.
