### ISSUE TITLE
Events: save start/end of a period to the database

### ISSUE THREAD

**Issue by tillprochaska** [roschaefer/story.board#406]
In the current implementation, events have a `last_happened_at` property that is updated every time that particular event is triggered. Events are not directly connected to reports.

Therefore, when an event happens and there are text components triggered by that event, they will become active across all reports.

For example, when a calf is born on the organic farm, the respective text components will be shown in all three reports.

I’m pretty sure that this isn’t the desired behaviour. A possible solution would be to have EventTypes and Events, similar to the relation between Sensors and SensorReadings. Every Event belongs to a report and every EventType can have multiple events. A new event is created everytime that EventType ist triggered.

// cc @drjakob

**Comment by drjakob** [comment]
Events are defined as 1. happening once in a reports run time 2. and are manually activated. They are like switches.
1. Yes, events should be directly connected to reports (see #398)
2. For Events like "Springtime" the described Meta-behaviour could be useful. 
2. I don't understand whatfor we need Eventy Types. With the proposed behaviour there would be no significant difference left between events ans sensor?

**Comment by drjakob** [comment]
Okay, thought about it, you have a point. For the "Going back in time" function it would be nice if events log on/off positions like sensors.

**Comment by drjakob** [comment]
New Defintion? Events are defined by
1. have two states (hapened and not happened). Default is not happend. 2. and are manually switched. 3. They can tell about their status for every point in time as o nor off.

**Comment by roschaefer** [comment]
Here's how the step function of an event would look like over time: 


![](https://i.stack.imgur.com/RhweU.png)

**Comment by roschaefer** [comment]
@drjakob is it Ok if I rename `Event` to `Situation` and use the name `Event` for the child model? So one situation has many events?

**Comment by tillprochaska** [comment]
Other naming ideas for child models: `EventRelease` or `EventActivation`. This wouldn’t require a naming change that editors might have to get used to first and there’s a clear relation between the parent and child models. Sounds a bit awkward, though.

**Comment by drjakob** [comment]
@roschaefer yes. So Birth is a Situation and Birth_start_beeing_in labor, birth_temperature_decrease and birth_succesful  will be Events?

**Comment by roschaefer** [comment]
No, `Low ingestion` is a situation and there will be many events when a cow wasn't eating enough. We can also stick to @tillprochaska namings.
