### ISSUE TITLE
BUG order of q&as in create tcs

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#413]
Q&As in modal create text component are now displayed in wrong order. Should be 
1. Q&A
2. Q&a
3. Q&A

(It has been correct. Who changed this?)

**Comment by roschaefer** [comment]
Can you tell us the id of the text component and the expected behaviour?

BTW: there is no enforced order of Q&A so far.

**Comment by roschaefer** [comment]
When #415 is deployed, is this bug still occurring?
