### ISSUE TITLE
BUG CHATFUEL-API just play one q&a

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#414]
Chatfuel now plays out ONE q&a instead of all q&as one after another.

This already worked perfect. Who changed this and why?

**Comment by roschaefer** [comment]
I can confirm that if you GET https://redaktion.superkuehe.de/reports/1/chatfuel/milk_quantity the server responds with text component 42 and its last question_answer. The first question_answer would be expected.

It's likely because of no natural ordering of `QuestionAnswer` in the database.

**Comment by drjakob** [comment]
So please order them in fixed order (eg .by id would be sufficient for the moment) which must be the same order displayed.

-- 
Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 720 50 27

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage
