### ISSUE TITLE
Missing sensory data

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#421]
As a reporter
I want to define a default text for missing sensory data for every sensor type (instead "missing sensory data --."
In order to better inform my readers in German language.

**Comment by tillprochaska** [comment]
Could you give an example of the text you’d like to be displayed, e. g. if there is no data available for the milk quantity sensor?

**Comment by drjakob** [comment]
Example: "Sorry, ich seh grad die Anzeige vom Melkstand nicht."

**Comment by tillprochaska** [comment]
So in the case of the follow part of a text component…

> Heute waren es {value(39)} Milch.

… you’d want the replaced string to look like the following?

> Heute waren es (Sorry, ich sehe gerade die Anzeige vom Melkstand nicht.)

Or is it that you want some kind of conditionals?

> {#if value(39)}Heute waren es {value(39)} Milch{#else}Sorry, ich sehe gerade die Anzeige vom Melkstand nicht.{/if}

**Comment by drjakob** [comment]
First option (with better text)

-- 
Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 720 50 27

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage

**Comment by tillprochaska** [comment]
Okay, I’d propose a markup syntax like this: `Heute war es { value(42) | Fallback } warm.` Is the pipe character safe to use or is it possible that someone might use it in the fallback content.

The above example would render as follows
- Given a sensor reading `24`: `Heute war es 24 °C warm`
- Without a sensor reading: `Heute war es Fallback warm`

**Comment by roschaefer** [comment]
looks nice, but I guess that's way too expensive to implement - how about a setting in the sensor?

**Comment by tillprochaska** [comment]
@roschaefer: If I understood correctly @drjakob would like to set the fallback depending on the context, right?

Do you mean expensive in terms of "expensive to process during the report generation" or implementation time?

I’ve written a test, slightly extended the regex to markup and it seems to work fine. It’s been 1 or 1.5 h of work so far. The text editor needs to be extended to highlight the new markup as well, but that shouldn’t be too much work.

**Comment by roschaefer** [comment]
@tillprochaska up to you. If you think that's within reason go for it. But in that case I would expect rspec tests for the markup.

**Comment by roschaefer** [comment]
and by "expensive" I mean many things at once: Implementation time, increased complexity of the code base, potential error causes - compared to the value for the customer

**Comment by tillprochaska** [comment]
@roschaefer: ✅

I’ll grab something for lunch, then do the ui part and submit a PR so you can have a look at it.

**Comment by roschaefer** [comment]
and you have to consider the briefing for the users - this feature is only worth if the editors understand and use it
