### ISSUE TITLE
Sensor#edit Animal ID should work for many sensors

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#450]
The Animal Id (as I understand it) should be usable for all of the animals sensors. At the moment I get an error if i try to use the same animal id for another sensor: (Animal id has already been taken).

**Comment by matthib** [comment]
There can only be one sensor with a specific type per animal id. So I can have a temperature sensor (https://redaktion.superkuehe.de/reports/1/sensors/95) and a motion sensor (https://redaktion.superkuehe.de/reports/1/sensors/96)  with the same animal id, but not two temperature sensors with the same animal id.

**Comment by drjakob** [comment]
Ok.
