### ISSUE TITLE
Report: Fix naming issues of enum column `intention`

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/story.board#452]
All the sensory data is divided into currently two sets: One set of data coming from real sensors and one set of generated data for debugging purposes. The data for debugging will be used only for the `preview` version of the report and the actual data for the `present` version of the report.

The naming is very confusing and misleading within the team. Therefore let's fix these naming isssues:

# Renamings
column intention => release
value real => final
value fake => debug
route present => final
route preview => debug

**Comment by drjakob** [comment]
Ok

-- 
Dr. Jakob J. E. Vicari
freier Wissenschaftsredakteur
post@jakobvicari.de
+49 (0)4131 720 50 27

Wissenschaftsjournalist des Jahres 2015, Medium Magazin
Sieger Formatfestival 2015, Medieninnovationszentrum Babelsberg
Nominiert Nannen-Preis 2016, Web-Reportage

**Comment by roschaefer** [comment]
I changed `version` to `release`, feels slightly more expressive...
