### ISSUE TITLE
TextComponent#edit: Include link to images

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#458]
As a reporter
I want to embed certain photos i uploaded on instagram in my sensorstory
in order to use images.

CONFIRM WITH @DavidLichtenberger

**Comment by roschaefer** [comment]
@DavidLichtenberger we're discussing if we want to allow HTML in text components. Right now, editors already put in arbitary html like: 
```
If you want to learn more about this read here <a href="blabla"></a>
```
Instagram links would be pasted in a similar way.

What's your opinion? Would you allow unsafe html? Do you want a different markup like [ markdown ] ( url )?

**Comment by DavidLichtenberger** [comment]
See my [comment on Issue 428](https://github.com/roschaefer/story.board/issues/428#issuecomment-317561592)

**Comment by drjakob** [comment]
Instagram embed Links in Wordpress look like: https://api.instagram.com/oembed?url=http://instagr.am/p/fA9uwTtkSN/ (source: https://www.instagram.com/developer/embedding/). So its most convenient for editors to copy&paste it.

**Comment by matthib** [comment]
@drjakob The image upload was realized with the text component image upload. Is this issue still relevant, or can it be closed?
