### ISSUE TITLE
Adjustable text input

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#491]
As a reporter (Björn)
I want to have a adjustable input field for sensorstory-Main-text
In order to write snd edit longer texts.

**Comment by tillprochaska** [comment]
Is there anything missing in the way it’s currently solved?

![autosize_textarea](https://user-images.githubusercontent.com/1512805/28490920-f4131942-6ee5-11e7-9d76-5d0797634376.gif)

**Comment by drjakob** [comment]
Yes: main should be 8 lines high as default
And: it should have a expander-edge to expand it with mouse (if possible)

**Comment by tillprochaska** [comment]
A larger main field by default is no problem at all. But we had text inputs that we’re resizable by dragging the corners with the mouse before, I think, but wanted a different solution, right?

Of course I can revert this (would be a pretty simple change, actually), but I think the current solution provides a much better UX as it doesn’t require you to manually resize the textarea, but resizes automatically to fit the content.

Maybe I just set a larger default size on the main field first and we’ll see if there is an additional need to resize the inputs manually afterwards?

**Comment by roschaefer** [comment]
A text input field with large space by default may suggest to the user that it is important to write a long text here. But it is not important, it is actually pretty bad. E.g. the current generated report at http://redaktion.superkuehe.de/reports/present/4 has a massive size at around `11299` characters. Who is going to read this?

**Comment by drjakob** [comment]
No @roschaefr, the actual report ist not correct generated because of missing event architecture and trigger dfeinitions.

**Comment by drjakob** [comment]
A bigger default size would be perfect.
I think editors often work as follows: resize input to a big, empty page and then start writing. Its just psychology. So the resizeing corner option would be good.

**Comment by roschaefer** [comment]
You are the journalists and know better what's a good size for a readable `text_component` - we can have a large text input field by default. Just keep the considerations in mind.

**Comment by drjakob** [comment]
Yes, but our text length is strictly defined already. Just not yet implemented on editorial side.
