### ISSUE TITLE
Add sensortype RFID Reader

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#499]
As a storytrolley editor
I wnat to have a sensortype RFID Reader (containing read IDs)
In order to use RFID-tagged objects as controlers for my storytrolley.

**Comment by matthib** [comment]
@drjakob I don't quite understand the read IDs. Does this mean the read IDs need to be stored, just like the animal IDs, by entering them in the form and saving them in the db with a RFID Reader sensor?

**Comment by drjakob** [comment]
The RFID IDs are the measured values. Every tag has a unique ID like "100015" or "200034" or "456709". So nothing to worry about. (We are defining the source later.)
