### ISSUE TITLE
BUG Wrong Links for current report

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#505]
Links for current report "Liee view" and "Preview" always link to views for report 1,
Should link to current report views.

**Comment by roschaefer** [comment]
![selection_001](https://user-images.githubusercontent.com/2110676/28502849-a9b3caf6-6ffb-11e7-98bc-21e83f2a876e.png)


@tillprochaska better you use rails link helpers. Run `bin/rails routes`. On the very left side, you see names like `edit_trigger_report`. If you add `_path`, that's the name for the rails link helper. So in our case `present_report_path(Report.current)`. See e.g. [the rails guides](http://guides.rubyonrails.org/routing.html#prefixing-the-named-route-helpers).
