### ISSUE TITLE
PERFORMANCE: TextComponents#index page load time way too long

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#513]
The list of tcs is rendered really slow (or not at all) because of pre-rendering of tc-edit-modal.

**Comment by drjakob** [comment]
http://redaktion.superkuehe.de/reports/4/text_components

**Comment by roschaefer** [comment]
as discussed, we just remove the modal and get rid of the performance issues

**Comment by drjakob** [comment]
Killed "Create with new Trigger" function and character counter.
