### ISSUE TITLE
BRING BACK JAVA SCRIPT FUNCTIONS

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#558]
BRING BACK JAVA SCRIPT FUNCTIONS for tc create

**Comment by roschaefer** [comment]
?

**Comment by roschaefer** [comment]
We can merge https://github.com/roschaefer/story.board/pull/542 and do the rest later if you like.

**Comment by tillprochaska** [comment]
@drjakob: This was probably related to the functionality in the text component edit views, right? If there are any remaining issues, please reopen.
