### ISSUE TITLE
Reset Report-Archive on Sept.3rd (=Start-date)

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#613]
Project start is sept 4th. So please rseset report archive for all four reports on sept 3st

**Comment by roschaefer** [comment]
we have a UI for that 
![report_settings](https://user-images.githubusercontent.com/2110676/29687086-80936f76-891b-11e7-9fd1-5a5bbb024654.png)

**Comment by drjakob** [comment]
No, this don't work. We have entries in frontend now despite the fact that the start date is set to 4th of septembr. This is ok. There should be content between 1st and 4th of september. But the reports before should not be shown.. There is no function for that. I think its possible to show reports for january, 1st 1900 or june 30th 1974. But we want to have a limit in "scroll back in time". This should be start date - 3

**Comment by drjakob** [comment]
Now start date is the date of deployment.

**Comment by drjakob** [comment]
Now start date you get reports for is the date of deployment.
