### ISSUE TITLE
BUG Alert-Trigger gets lost

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#639]
BUG: This is a serious bug. 
The Alert (calving will start in 6 hours, sensor (ALERT_Smaxtec_Kalbung_Emma:KuhNr.206_HofHoeck", ID 111), triggered by "Emma Alarm: Geburtsalarm hat ausgelöst. Geburt ist in 6 bis 12 Stunden erwartet"  has been displayed yesterday, 16'00 on the page of Emma. Now its gone. WHY? active Triggers should be stable in history! Otherwise the scroll-back-function has no value if important things gets lost.

**Comment by matthib** [comment]
@drjakob So the problem is that this trigger was activated on th 29th of August at 16:00 on the diary page of Emma showing the birth warning and now if I go back to the diary entry at that time the trigger  (or the text components which the trigger activated) are not shown anymore in the diary entry, is that correct?

**Comment by drjakob** [comment]
Correct

**Comment by drjakob** [comment]
This would be a nice fix before launch on monday for the system to work properly!

**Comment by matthib** [comment]
@drjakob Could you you give me the ids of the text components you expected to show up in the diary entry for the calving alert?

**Comment by drjakob** [comment]
199 for report 3

**Comment by tillprochaska** [comment]
@matthib: I think [this line](https://github.com/roschaefer/story.board/blob/master/app/models/trigger.rb#L29) is the reasons for the bug. The `conditions_fulfilled` doesn’t take the moment of the `diary_entry` into account. I think something like this could solve this:

```ruby
(validity_period.nil? || (diary_entry.moment - validity_period.hours <= reading.created_at))
```

**Comment by tillprochaska** [comment]
Using the current production data, this should be the URL to the relevant diary entry: http://localhost:3000/reports/5/diary_entries/6124.json (2017-08-29 16:00)

Report ID: 5
Text Component ID: 192
Trigger ID: 344
Sensor ID: 111

**Comment by matthib** [comment]
@tillprochaska Yes, I guess that makes sense and your suggestion to fix it probably works. I don't have the time atm to try it out, but we should definately gie it a try!

**Comment by drjakob** [comment]
Great!
