### ISSUE TITLE
Delete JSON-TimeMarker 15 o'clock

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#659]
We don't have a timespan for 15 o'clock. So please don't generate a diary.

**Comment by tillprochaska** [comment]
Okay, I’m a bit confused now… The cronjob runs the archive task every day at 6:05, 9:05, 13:05, 18:05, 23:05, 3:05, but not at 15:05. @roschaefer, any ideas?

**Comment by drjakob** [comment]
I think 3:05 is set to pm, not a.m? (Delete 3:05)

**Comment by tillprochaska** [comment]
Okay, that might be an idea, but it’s still confusing as everything is using a 24h-system.

**Comment by roschaefer** [comment]
I copy pasted the dates from https://github.com/roschaefer/story.board/issues/612 in https://github.com/roschaefer/story.board/pull/632. No entry in the afternoon or at night then?

**Comment by tillprochaska** [comment]
Nope, @drjakob want’s the diary entries to correspond to the timeframes for text components:

(06:00 - 09:00) in the morning
(09:00 - 13:00) before noon
(13:00 - 18:00) afternoons
(18:00 - 23:00) evenings
(23:00 - 06:00)
