### ISSUE TITLE
Still cant change associated report in tc

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#669]
BUG The choice of the associated report in create tc menu still don't work. it changes the dropdown (stable after saving and re-editing) but the tcs seem still connected to the original (wrong) report.
See this tc: 
1. It has been created in report 4. (Human Error)
2. But it should be connected to report 5, so I changed it in edit->report dropdown. 
3. It says its connected to 5. But is still connected to report 4.
![bildschirmfoto 2017-09-06 um 08 02 26](https://user-images.githubusercontent.com/11591426/30096691-2b9eaa1c-92da-11e7-965c-aeb262226b27.JPG)

**Comment by roschaefer** [comment]
Are you sure the wrong report is connected? If you change the `:report_id` in the URL, you can still see the text component form. Actually, that's the biggest problem here: You can change the `:report_id` but the URL is not updated. So the menu still shows the old report.

But the report in the dropdown menu is the report of the text component.

**Comment by tillprochaska** [comment]
Should be enough to redirect to the report_text_component_path

**Comment by tillprochaska** [comment]
Oh, I submitted that one by accident and can't edit it from my phone. Should be enough Tonkonserve the redirect path in the TextComponent controller update action to redirect to the texts components report and not to the current report.
