### ISSUE TITLE
Change of Sensor-Menu

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#67]
As a member of service team i want

to define sensor*boxes* with unique I2C adresses to 
easily connect sensorboxes to reporter.box

**Comment by roschaefer** [comment]
First question: Is it worth to add another entity? I would ask @kabel42 for opinions.
Second question: How to call it? I would vote against *sensor-box* to avoid confusion. Maybe sensor-device?

**Comment by drjakob** [comment]
sensor-unit?

**Comment by roschaefer** [comment]
so the physical device is called *sensor-device* and the actual sensor is called *sensor-unit*?

**Comment by roschaefer** [comment]
obsolete
