### ISSUE TITLE
CONFLICT: night timeframe conflicting in planing with days

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#677]
There is a conflict with timeframe night (23-6 o'clock) and days.

As an editor 
planing to publish a tc in the night of day 3 to 4 I choose timeframe night (23-6) and day 3 to four.
BUT then tc will also be active from 23-23:59) on day 4.
Possible Solution: changeing night-timeframe to 0-6 
 
What do you think?

**Comment by tillprochaska** [comment]
Seems like a good and quite simple solution. 👍

**Comment by matthib** [comment]
I agree, changing it to 0-6 is probably the best solution, so it doesn't interfere with the next day.

**Comment by drjakob** [comment]
Ok, feel free to change it!
