### ISSUE TITLE
TextComponent: Add timeliness constraint

### ISSUE THREAD

**Issue by drjakob** [roschaefer/story.board#76]
As a journalist
I want to define that a text component will be triggered only for a recent sensor reading
Because e.g. a loud noise from five days ago is not relevant anymore

**Comment by roschaefer** [comment]
How about saving sensor peaks? The system could look for a sensor peak e.g. within the last 3 hours.

**Comment by roschaefer** [comment]
In the backend, the reporting team will have to define what exactly makes a peak.

**Comment by drjakob** [comment]
As member of service team I need to define "peak-intervall" in sensor definition
to iidentify peaks for different sensors.

**Comment by drjakob** [comment]
Now: job of the sensor himselft. BUT we need AGE of measurement
