### ISSUE TITLE
Sensor#create: Select Sensor Type and Sensor-ID

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/story.board#9]
As journalist
I want to configure my sensors from a pre-known set of available sensor types and simple sensor IDs [e.g. "AIR21"].
So I have less trouble with configuration

**Comment by drjakob** [comment]
journalist should not work with things like I2C addresses.

**Comment by roschaefer** [comment]
Is that true? I talked to @kabel42 and I understood that we identify sensor readings by the sensor's [I2C address](https://en.wikipedia.org/wiki/I%C2%B2C) plus the box id. So, for one box, we can connect up to 128 sensors. We can however connect multiple boxes per experiment in the future. We, the service team will print the sensor's I2C id on the sensor case before shipping. The journalist can then enter the address in the dialog.

**Comment by drjakob** [comment]
Yes, we identify them by their address. But as a journalist I don't want to mess up with things like i2c addresses. The configuration of i2c addresses for sensors is the job of the service-team (see #32).

**Comment by drjakob** [comment]
We, the service team, will print a sensor ID on the boxes. 
SENSOR_ID = explanation

AIR21 = Air-Quality-Sensor 21 with I2C Address 3x456. 
AIR22 = Air-Quality-Sensor 22 with I2C Address 3x123.
AIR23 = Air-Quality-Sensor 23 with I2C Address 3x321.
TEMP25 =Temperature Sensor 25 with I2C Address 3x432.
TEMP26 =Temperature Sensor 25 with I2C Address 3x554.

**Comment by drjakob** [comment]
![](imap://wp1101780-jakob@mail.jakobvicari.de:143/fetch%3EUID%3E.SPAM%3E17649?part=1.2.2&filename=image1.JPG)

**Comment by drjakob** [comment]
![image1](https://cloud.githubusercontent.com/assets/11591426/15404827/a33ac430-1dff-11e6-8c55-eb101c8d5e1d.JPG)

**Comment by roschaefer** [comment]
Time spent: 2 hours
