### ISSUE TITLE
Report: Read about any point in time

### ISSUE THREAD

**Issue by roschaefer** [roschaefer/story.board#97]
As a reader
I want to read reports at any point back in time
Because I am interested in a certain moment in time

**Comment by drjakob** [comment]
Please keep PERFORMANCE issues in mind. Could be better to pre-generate reports than to gneerate them live while thousands of users are traveling through time.

**Comment by roschaefer** [comment]
Don't worry! There are a lot Rails apps out there that must handle a much bigger workload. If we ever run into performance issues, then we'll solve the problem as soon we have 'em. [Avoid premature optimization](http://c2.com/cgi/wiki?PrematureOptimization).
